// Angular/src/app/app.component.ts
import { Component, ViewChild, ViewChildren, QueryList } from '@angular/core';
import { Service, Customer } from './app.service'
import { DxDataGridComponent } from 'devextreme-angular';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  
})
export class AppComponent {
  customers: Array<Customer>;

  widgetCount: number;
  readyCtr: number;

  @ViewChildren(DxDataGridComponent) dataGrids: QueryList<DxDataGridComponent>;
  scrollableDg1;
  scrollableDg2;

  pageSize: number;
  allowedPageSizes: Array<number>;
  pageIndex: number;
  selectedRowKeys: Array<number>;

  columnFilterValues: any;
  columnSelectedFilterOps: any;
  columnSortOpts: any;

  prevColSorted: string;

  constructor(service: Service) {
    this.widgetCount = 2;
    this.readyCtr = 0;

    this.pageSize = 10;
    this.allowedPageSizes = [5, 10, 20];
    this.pageIndex = 0;

    this.columnFilterValues = service.initColumnOptions();
    this.columnSelectedFilterOps = service.initColumnOptions();
    this.columnSortOpts = service.initColumnOptions();
    
    this.customers = service.getCustomers();
  }

  onContentReady(e) {
    if (this.readyCtr < this.widgetCount) {
      this.readyCtr++;
    }
    if (this.readyCtr === this.widgetCount) {
      this.readyCtr++;
      this.initScrollable();
    }
  }

  onOptionChanged(e) {
    if (e.fullName.includes("sortOrder")) {
      let colIdx = parseInt(e.fullName.slice(8, 9)),
        dataField = e.component.columnOption(colIdx, "dataField");
      
      this.dataGrids.last.instance.beginUpdate();
      if(this.prevColSorted && this.prevColSorted !== dataField) {
        this.columnSortOpts[this.prevColSorted] = null;
      }
      this.columnSortOpts[dataField] = e.value;
      this.dataGrids.last.instance.endUpdate();
      
      this.prevColSorted = dataField
    }
  }

  initScrollable() {
    this.scrollableDg1 = this.dataGrids.first.instance.getScrollable();
    this.scrollableDg2 = this.dataGrids.last.instance.getScrollable();
  
    this.scrollableDg1.on("scroll", function (e) {
      this.scrollableDg2.scrollTo(e.scrollOffset);
    }.bind(this));
  }

}

<div class="tables">
    <div class="column">
        <dx-data-grid [dataSource]="customers" keyExpr="ID" [showBorders]="true" [height]="440"
            [(selectedRowKeys)]="selectedRowKeys" (onContentReady)="onContentReady($event)" 
            (onOptionChanged)="onOptionChanged($event)">
            <dxo-paging [enabled]="true" [(pageSize)]="pageSize" [(pageIndex)]="pageIndex"></dxo-paging>
            <dxo-pager [visible]="true" [showPageSizeSelector]="true" [allowedPageSizes]="allowedPageSizes"
                [showInfo]="true">
            </dxo-pager>
            <dxo-filter-row [visible]="true"></dxo-filter-row>
            <dxo-selection mode="single"></dxo-selection>
            <dxi-column dataField="CompanyName" [(selectedFilterOperation)]="columnSelectedFilterOps.CompanyName"
                [(filterValue)]="columnFilterValues.CompanyName"></dxi-column>
            <dxi-column dataField="City" [(selectedFilterOperation)]="columnSelectedFilterOps.City"
                [(filterValue)]="columnFilterValues.City"></dxi-column>
            <dxi-column dataField="State" [(selectedFilterOperation)]="columnSelectedFilterOps.State"
                [(filterValue)]="columnFilterValues.State"></dxi-column>
            <dxi-column dataField="Phone" [(selectedFilterOperation)]="columnSelectedFilterOps.Phone"
                [(filterValue)]="columnFilterValues.Phone"></dxi-column>
            <dxi-column dataField="Fax" [(selectedFilterOperation)]="columnSelectedFilterOps.Fax"
                [(filterValue)]="columnFilterValues.Fax"></dxi-column>
        </dx-data-grid>
    </div>
    <div class="column">
        <dx-data-grid [dataSource]="customers" keyExpr="ID" [showBorders]="true" [height]="440"
            [selectedRowKeys]="selectedRowKeys" (onContentReady)="onContentReady($event)">
            <dxo-paging [enabled]="true" [pageSize]="pageSize" [pageIndex]="pageIndex"></dxo-paging>
            <dxo-pager [visible]="true" [showPageSizeSelector]="true" [allowedPageSizes]="allowedPageSizes"
                [showInfo]="true">
            </dxo-pager>
            <dxo-filter-row [visible]="true"></dxo-filter-row>
            <dxo-selection mode="single"></dxo-selection>
            <dxi-column dataField="CompanyName" [selectedFilterOperation]="columnSelectedFilterOps.CompanyName"
                [filterValue]="columnFilterValues.CompanyName" [sortOrder]="columnSortOpts.CompanyName"
                [sortIndex]="columnSortOpts.CompanyName"></dxi-column>
            <dxi-column dataField="City" [selectedFilterOperation]="columnSelectedFilterOps.City"
                [filterValue]="columnFilterValues.City" [sortOrder]="columnSortOpts.City"></dxi-column>
            <dxi-column dataField="State" [selectedFilterOperation]="columnSelectedFilterOps.State"
                [filterValue]="columnFilterValues.State" [sortOrder]="columnSortOpts.State"></dxi-column>
            <dxi-column dataField="Phone" [selectedFilterOperation]="columnSelectedFilterOps.Phone"
                [filterValue]="columnFilterValues.Phone" [sortOrder]="columnSortOpts.Phone"></dxi-column>
            <dxi-column dataField="Fax" [selectedFilterOperation]="columnSelectedFilterOps.Fax"
                [filterValue]="columnFilterValues.Fax" [sortOrder]="columnSortOpts.Fax"></dxi-column>
        </dx-data-grid>
    </div>
</div>

// Vue/src/App.vue
<template>
<div class="tables">
    <div class="column">
      <DxDataGrid
        ref="dataGrid1"
        :data-source="dataSource"
        key-expr="ID"
        :show-borders="true"
        :height="440"
        :selected-row-keys.sync="selectedRowKeys"
        @content-ready="onContentReady($event)" 
        @option-changed="onOptionChanged($event)"
      >
        <DxPaging :enabled="true" :page-size.sync="pageSize" :page-index.sync="pageIndex"/>
        <DxPager
          :visible="true"
          :show-page-size-selector="true"
          :allowed-page-sizes="allowedPageSizes"
          :show-info="true"
        />
        <DxFilterRow :visible="true" />
        <DxSelection mode="single" />

        <DxColumn dataField="CompanyName" :selectedFilterOperation.sync="columnSelectedFilterOps.CompanyName"
            :filterValue.sync="columnFilterValues.CompanyName" />
        <DxColumn dataField="City" :selectedFilterOperation.sync="columnSelectedFilterOps.City"
            :filterValue.sync="columnFilterValues.City" />
        <DxColumn dataField="State" :selectedFilterOperation.sync="columnSelectedFilterOps.State"
            :filterValue.sync="columnFilterValues.State" />
        <DxColumn dataField="Phone" :selectedFilterOperation.sync="columnSelectedFilterOps.Phone"
            :filterValue.sync="columnFilterValues.Phone" />
        <DxColumn dataField="Fax" :selectedFilterOperation.sync="columnSelectedFilterOps.Fax"
            :filterValue.sync="columnFilterValues.Fax" />
      </DxDataGrid>
    </div>
    <div class="column">
      <DxDataGrid
        ref="dataGrid2"
        :data-source="dataSource"
        key-expr="ID"
        :show-borders="true"
        :height="440"
        :selected-row-keys="selectedRowKeys"
        @content-ready="onContentReady($event)" 
      >
        <DxPaging :enabled="true" :page-size="pageSize" :page-index="pageIndex"/>
        <DxPager
          :visible="true"
          :show-page-size-selector="true"
          :allowed-page-sizes="allowedPageSizes"
          :show-info="true"
        />
        <DxFilterRow :visible="true" />
        <DxSelection mode="single" />

        <DxColumn dataField="CompanyName" :selectedFilterOperation="columnSelectedFilterOps.CompanyName"
            :filterValue="columnFilterValues.CompanyName" :sort-order="columnSortOpts.CompanyName"/>
        <DxColumn dataField="City" :selectedFilterOperation="columnSelectedFilterOps.City"
            :filterValue="columnFilterValues.City" :sort-order="columnSortOpts.City" />
        <DxColumn dataField="State" :selectedFilterOperation="columnSelectedFilterOps.State"
            :filterValue="columnFilterValues.State" :sort-order="columnSortOpts.State"/>
        <DxColumn dataField="Phone" :selectedFilterOperation="columnSelectedFilterOps.Phone"
            :filterValue="columnFilterValues.Phone" :sort-order="columnSortOpts.Phone"/>
        <DxColumn dataField="Fax" :selectedFilterOperation="columnSelectedFilterOps.Fax"
            :filterValue="columnFilterValues.Fax" :sort-order="columnSortOpts.Fax"/>
      </DxDataGrid>
    </div>
</div>
</template>

<script>
import { DxDataGrid, DxColumn, DxPager, DxPaging, DxFilterRow, DxSelection } from 'devextreme-vue/data-grid';
import service from './data.js';

let scrollableDg1, scrollableDg2;
let widgetCount = 2,
      readyCtr = 0;
let prevColSorted;

export default {
  components: {
    DxDataGrid,
    DxColumn,
    DxPager,
    DxPaging,
    DxFilterRow,
    DxSelection
  },
  data() {
    return {
      dataSource: service.getCustomers(),
      pageSize: 10,
      allowedPageSizes: [5, 10, 20],
      pageIndex: 0,
      columnFilterValues: service.initColumnOptions(),
      columnSelectedFilterOps: service.initColumnOptions(),
      columnSortOpts: service.initColumnOptions(),
      selectedRowKeys: []
      
    };
  },
  methods: {
    onContentReady() {
      if (readyCtr < widgetCount) {
        readyCtr++;
      }
      if (readyCtr === widgetCount) {
        readyCtr++;
        this.initScrollable();
      }
    },
    onOptionChanged(e) {
      if (e.fullName.includes("sortOrder")) {
        let colIdx = parseInt(e.fullName.slice(8, 9)),
          dataField = e.component.columnOption(colIdx, "dataField");
        
        this.dataGrid2.beginUpdate();
        if(prevColSorted && prevColSorted !== dataField) {
          this.columnSortOpts[prevColSorted] = null;
        }
        this.columnSortOpts[dataField] = e.value;
        this.dataGrid2.endUpdate();

        prevColSorted = dataField;
      }
    },
    initScrollable() {
      scrollableDg1 = this.dataGrid1.getScrollable();
      scrollableDg2 = this.dataGrid2.getScrollable();
    
      scrollableDg1.on("scroll", function (e) {
        scrollableDg2.scrollTo(e.scrollOffset);
      }.bind(this));
    }
  },
  computed: {
    dataGrid1() {
      return this.$refs.dataGrid1.instance;
    },
    dataGrid2() {
      return this.$refs.dataGrid2.instance
    }
  }
}
</script>

<style>
.tables {
    display: flex;
}

.column:first-child {
    width: 50%;
    padding-right: 15px;
}

.column:last-child {
    width: 50%;
    padding-left: 15px;
}
</style>
